#!/bin/bash

# time ~/hwmc20-mlir/runbench/run_btor.sh ~/hwmc20-mlir/runbench/bv/btor_19_beem.set btor2mlir_bv_19_beem
# time ~/hwmc20-mlir/runbench/run_btor.sh ~/hwmc20-mlir/runbench/bv/btor_19_goel.set btor2mlir_bv_19_goel
# time ~/hwmc20-mlir/runbench/run_btor.sh ~/hwmc20-mlir/runbench/bv/btor_19_mann.set btor2mlir_bv_19_mann
# time ~/hwmc20-mlir/runbench/run_btor.sh ~/hwmc20-mlir/runbench/bv/btor_18D_wolf.set btor2mlir_bv_18D_wolf
# time ~/hwmc20-mlir/runbench/run_btor.sh ~/hwmc20-mlir/runbench/bv/btor_19A_wolf.set btor2mlir_bv_19A_wolf
# time ~/hwmc20-mlir/runbench/run_btor.sh ~/hwmc20-mlir/runbench/bv/btor_19B_wolf.set btor2mlir_bv_19B_wolf
# time ~/hwmc20-mlir/runbench/run_btor.sh ~/hwmc20-mlir/runbench/bv/btor_19C_wolf.set btor2mlir_bv_19C_wolf
# time ~/hwmc20-mlir/runbench/run_btor.sh ~/hwmc20-mlir/runbench/bv/btor_20.set btor2mlir_bv_20

# time ~/hwmc20-mlir/runbench/run_btor.sh ~/hwmc20-mlir/runbench/array/btor_18A_wolf.set btor2mlir_array_18A_wolf
# time ~/hwmc20-mlir/runbench/run_btor.sh ~/hwmc20-mlir/runbench/array/btor_19A_wolf.set btor2mlir_array_19A_wolf
# time ~/hwmc20-mlir/runbench/run_btor.sh ~/hwmc20-mlir/runbench/array/btor_19B_wolf.set btor2mlir_array_19B_wolf
# time ~/hwmc20-mlir/runbench/run_btor.sh ~/hwmc20-mlir/runbench/array/btor_19C_wolf.set btor2mlir_array_19C_wolf
# time ~/hwmc20-mlir/runbench/run_btor.sh ~/hwmc20-mlir/runbench/array/btor_19_mann.set btor2mlir_array_19_mann
time ~/hwmc20-mlir/runbench/run_btor.sh ~/hwmc20-mlir/runbench/array/btor_20.set btor2mlir_array_20